name: IndexNow
on:
  schedule:
    - cron: '0 2 * * *'  # مرة واحدة في اليوم الساعة 2
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit latest URLs only (not all)
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: https://zero-tv.pages.dev/sitemap.xml
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: https://zero-tv.pages.dev/${{ secrets.INDEXNOW_KEY }}.txt
          since: 1
          since-unit: day
          # ضيف دول عشان ميبعتش كله
          endpoint: api.indexnow.org
