name: IndexNow

on:
  push:
    branches: [ main ]

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit to IndexNow
        uses: bojieyang/indexnow-action@v2        with:
          sitemap-location: 'https://zero-tv.pages.dev/sitemap.xml'
          key: '5468bcf493cc45ad840c9598df986663'
          key-location: 'https://zero-tv.pages.dev/5468bcf493cc45ad840c9598df986663.txt'
