name: IndexNow
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'public/sitemap.xml'

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit last 1 day only
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: https://zero-tv.pages.dev/sitemap.xml
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: https://zero-tv.pages.dev/${{ secrets.INDEXNOW_KEY }}.txt
          since: 1
          since-unit: day
